export default {
  "login": "MortezaFathnia",
  "id": 16924889,
  "node_id": "MDQ6VXNlcjE2OTI0ODg5",
  "avatar_url": "https://avatars.githubusercontent.com/u/16924889?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/MortezaFathnia",
  "html_url": "https://github.com/MortezaFathnia",
  "followers_url": "https://api.github.com/users/MortezaFathnia/followers",
  "following_url": "https://api.github.com/users/MortezaFathnia/following{/other_user}",
  "gists_url": "https://api.github.com/users/MortezaFathnia/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/MortezaFathnia/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/MortezaFathnia/subscriptions",
  "organizations_url": "https://api.github.com/users/MortezaFathnia/orgs",
  "repos_url": "https://api.github.com/users/MortezaFathnia/repos",
  "events_url": "https://api.github.com/users/MortezaFathnia/events{/privacy}",
  "received_events_url": "https://api.github.com/users/MortezaFathnia/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Morteza Fathnia",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 44,
  "public_gists": 0,
  "followers": 6,
  "following": 27,
  "created_at": "2016-01-27T18:46:16Z",
  "updated_at": "2022-11-07T10:38:18Z"
};
